easy_admin:
    list:
        actions: ['show']
    site_name: "<a href='http://127.0.0.1:8000/'><img src='/img/logo-kids.png' width='180' /></a>"
    design:
        menu:
            - { entity: 'Program', label: 'Programmes', icon: 'fas fa-chalkboard-teacher' }
            - { entity: 'Category', label: 'Catégories' }
            - { entity: 'User', label: 'Parents', icon: 'fas fa-users' }
            - { entity: 'Kids', label: 'Enfants', icon: 'fas fa-child' }
            - { entity: 'Workshop', label: 'Ateliers', icon: 'fas fa-puzzle-piece' }
            - { entity: 'Newsletter', icon: 'fas fa-envelope' }
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Program
        Program:
            class: App\Entity\Program
            list:
                fields:
                    - { property: 'name' }
                    - { property: 'description', type: 'text_editor' }
                    - { property: 'registration' }
                    - { property: 'startdate' }
                    - { property: 'category' }
                    - { property: 'important', type: 'text_editor' }
                    - { property: 'kids' }
                    - { property: 'places' }
#                    - { property: 'image', type: 'image', base_path: '/' }
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'registration', type: 'App\Form\CustomDateType', label: 'Inscription' }
                    - { property: 'startdate', type: 'App\Form\CustomDateType', label: 'Début' }
                    - { property: 'enddate', type: 'App\Form\CustomDateType', label: 'Fin' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'kids', label: 'Enfants' }
                    - { property: 'important', type: 'text_editor' }
                    - { property: 'places', label: 'Places disponibles' }
#                    - { property: 'image', type: 'file' }

#        - App\Entity\Category
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'slug' }
                    - { property: 'programs' }
                    - { property: 'workshops' }
                    - { property: 'minAge' }
                    - { property: 'maxAge' }
                    - { property: 'image', type: 'image', base_path: '/' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'description' }
                    - { property: 'slug' }
                    - { property: 'programs' }
                    - { property: 'workshops' }
                    - { property: 'minAge' }
                    - { property: 'maxAge' }
                    - { property: 'image', type: 'file', type_options: { data_class: null } }

#        - App\Entity\User
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'mail' }
                    - { property: 'password' }
                    - { property: 'kids' }
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'phone' }
#        - App\Entity\Kids
        Kids:
            class: App\Entity\Kids
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'user' }
                    - { property: 'birthday' }
                    - { property: 'programs' }
#        - App\Entity\Workshop
        Workshop:
            class: App\Entity\Workshop
            list:
                fields:
                    - { property: 'category'}
                    - { property: 'title' }
                    - { property: 'description', type: 'text_editor' }
                    - { property: 'article', type: 'text_editor' }
#                    - { property: 'image', type: 'image', base_path: '/' }
            form:
                fields:
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', type: 'text_editor' }

                    - { property: 'article', type: 'text_editor', label: 'Détails' }
#        - App\Entity\Newsletter
        Newsletter:
            class: App\Entity\Newsletter
            list:
                fields:
                    - { property: 'mail' }
#                   - { property: 'image', type: 'file'}
