easy_admin:
    list:
        actions: ['show']
    site_name: "<a href='http://127.0.0.1:8000/'><img src='/img/logo-kids.png' width='180' /></a>"
    design:
        menu:
            - { entity: 'Program', label: 'Programmes', icon: 'fas fa-chalkboard-teacher' }
            - { entity: 'Category', label: 'Catégories' }
            - { entity: 'User', label: 'Parents', icon: 'fas fa-users' }
            - { entity: 'Kids', label: 'Enfants', icon: 'fas fa-child' }
            - { entity: 'Workshop', label: 'Ateliers', icon: 'fas fa-puzzle-piece' }
            - { entity: 'Newsletter', icon: 'fas fa-envelope' }
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Program
        Program:
            class: App\Entity\Program
            list:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'description' }
                    - { property: 'registration', label: Ouverture d'inscription }
                    - { property: 'startdate', label: 'Début' }
                    - { property: 'category', label: 'Categories' }
                    - { property: 'important', type: 'text_editor' }
                    - { property: 'kids', label: 'Enfants' }
                    - { property: 'places', label: 'Places disponibles' }
#                    - { property: 'image', type: 'image', base_path: '/', label: 'Images' }
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'description', type: 'text_editor' }
                    - { property: 'registration', type: 'App\Form\CustomDateType', label: 'Inscription' }
                    - { property: 'startdate', type: 'App\Form\CustomDateType', label: 'Début' }
                    - { property: 'enddate', type: 'App\Form\CustomDateType', label: 'Fin' }
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'kids', label: 'Enfants' }
                    - { property: 'important', type: 'text_editor' }
                    - { property: 'places', label: 'Places disponibles' }
#                    - { property: 'image', type: 'file' }
#        - App\Entity\Category
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'description' }
                    - { property: 'slug' }
                    - { property: 'programs' }
                    - { property: 'workshops', label: 'Evénement' }
                    - { property: 'image', type: 'image', base_path: '/' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'description' }
                    - { property: 'slug' }
                    - { property: 'programs' }
                    - { property: 'workshops', label: 'Evénement' }
                    - { property: 'image', type: 'file', type_options: { data_class: null } }
#        - App\Entity\User
        User:
            class: App\Entity\User
            list:
                fields:
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prenom' }
                    - { property: 'mail', label: 'Email' }
                    - { property: 'kids', label: 'Enfant(s)' }
                    - { property: 'phone', label: 'Telephone' }
            form:
                fields:
                    - { property: 'mail', label: 'Email' }
                    - { property: 'password', label: 'Mot de passe' }
                    - { property: 'kids', label: 'Enfant(s)' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prenom' }
                    - { property: 'phone', label: 'Telephone' }
#        - App\Entity\Kids
        Kids:
            class: App\Entity\Kids
            list:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'user', label: 'Parents' }
                    - { property: 'birthday', label: 'Date de naissance' }
                    - { property: 'programs',label: 'Programe(s)' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'user', label: 'Parents' }
                    - { property: 'birthday', label: 'Date de naissance' }
                    - { property: 'programs' }
#        - App\Entity\Workshop
        Workshop:
            class: App\Entity\Workshop
            list:
                fields:
                    - { property: 'category'}
                    - { property: 'title', label: 'titre' }
                    - { property: 'description' }
                    - { property: 'article' }
#                    - { property: 'image', type: 'image', base_path: '/' }
            form:
                fields:
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', type: 'text_editor' }
                    - { property: 'article', type: 'text_editor', label: 'Détails' }
#        - App\Entity\Newsletter
        Newsletter:
            class: App\Entity\Newsletter
            list:
                fields:
                    - { property: 'article' }