easy_admin:
    site_name: "<img src='/img/logo-kids.png' width='180' />"
    entities:
        # List the entity class name you want to manage
        - App\Entity\Program
        - App\Entity\Category
        - App\Entity\User
        - App\Entity\Kids
